---
- hosts: all

  tasks:
  - include: tasks/zsh.yml

  - name: Install applications through Homebrew
    homebrew: name={{item}} state=present
    with_items:
    - wget
    - git
    - ack
    - python
    - node

  - name: Install applications through Homebrew casks
    homebrew_cask: name={{item}} state=present
    with_items:
    - flux
    - google-chrome
    - caffeine
    - iterm2
    - dropbox
    - google-drive
    - the-unarchiver
    - kindle
    - 1password
    # vm
    - virtualbox
    - docker
    - vagrant
    # programming
    - macvim
    - sublime-text
    - atom
    - sourcetree
    - android-studio
    - java
    - dash
    # communication
    - telegram
    - fuze
    - slack
    - skype
