---
- hosts: all
  tasks:

  - name: Install applications through Homebrew
    homebrew: name={{item}} state=present
    with_items:
    - wget
    - git
    - ack
    - python
    - zsh
    - node

  - name: Install applications through Homebrew casks
    homebrew_cask: name={{item}} state=present
    with_items:
    - flux
    - dash
    - google-chrome
    - sourcetree
    - fuze
    - caffeine
    - atom
    - android-studio
    - vagrant
    - java
    - virtualbox
    - iterm2
    - dropbox
    - google-drive
    - skype
    - the-unarchiver
    - macvim
    - sublime-text
