  - name: Show hidden files by default
    shell: 'defaults write com.apple.finder AppleShowAllFiles -bool true'

  - name: Save screenshots in PNG format
    shell: 'defaults write com.apple.screencapture type -string "PNG"'

  - name: Display full POSIX path as Finder window title
    shell: 'defaults write com.apple.finder _FXShowPosixPathInTitle -bool true'

  - name: Stop Photos from opening automatically
    shell: 'defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true'
