  - name: Install zsh
    homebrew: name=zsh state=present

  - name: Check current shell
    shell: 'echo $SHELL'
    register: current_shell
    changed_when: False
    sudo: no

  - name: Make zsh default
    shell: chsh -s /bin/zsh
    when: current_shell.stdout.find('/bin/zsh') == -1

  - name: Check oh-my-zsh is installed
    stat: path=~/.oh-my-zsh
    register: oh_my_zsh_installed

  - name: Install oh-my-zsh
    shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
    when: oh_my_zsh_installed.stat.exists == false
  # got it from https://github.com/craigmarvelley/macbook-provisioning/blob/master/playbook.yml
